"""Tests for ``scripts/validate_translation_dynamic.py`` on synthetic data.

The script fits a random-walk player ability with closed-form moment
estimators and a Kalman filter, on rows strictly before each scored season.
Each test checks one property the estimator must have on ANY data generated by
the model it claims to fit, and names the mutation that breaks it; every
mutation was applied to the script, confirmed to fail, and reverted.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

import scripts.validate_translation_dynamic as vtd
import scripts.validate_translation_hierarchical as vth

pytestmark = pytest.mark.guard

LEAGUES = ("euroleague", "eurocup", "spain-acb", "italy-lba")
BETA = {"euroleague": 0.0, "eurocup": -1.0, "spain-acb": -1.5, "italy-lba": -2.5}
MU, TAU2, Q, SIGMA2 = 10.0, 4.0, 1.0, 40.0


def _simulate(seed: int, n_players: int = 2500, seasons=tuple(range(2016, 2021))):
    """Stints and same-season pairs from a random-walk ability, additive leagues."""
    rng = np.random.default_rng(seed)
    stints, pairs = [], []
    for p in range(n_players):
        a = rng.normal(MU, np.sqrt(TAU2))
        first = True
        for s in seasons:
            if not first:
                a += rng.normal(0, np.sqrt(Q))
            first = False
            lg = rng.choice(LEAGUES)
            g = int(rng.integers(8, 30))
            r1 = a + BETA[lg] + rng.normal(0, np.sqrt(SIGMA2 / g))
            stints.append(_stint(p, s, lg, g, r1))
            if rng.random() < 0.3:
                lg2 = rng.choice([x for x in LEAGUES if x != lg])
                g2 = int(rng.integers(8, 30))
                r2 = a + BETA[lg2] + rng.normal(0, np.sqrt(SIGMA2 / g2))
                stints.append(_stint(p, s, lg2, g2, r2))
                for (ld, rd), (lc, rc) in (
                    ((lg, r1), (lg2, r2)),
                    ((lg2, r2), (lg, r1)),
                ):
                    if ld not in ("euroleague", "eurocup") and lc in (
                        "euroleague",
                        "eurocup",
                    ):
                        pairs.append(
                            {
                                "player_name": f"p{p}",
                                "season": s,
                                "league_src": ld,
                                "league_dest": lc,
                                "pir_per36_src": rd,
                                "pir_per36_dest": rc,
                                "minutes_src": 450.0,
                                "minutes_dest": 450.0,
                            }
                        )
    return pd.DataFrame(stints), pd.DataFrame(pairs)


def _stint(p, s, lg, g, rate):
    return {
        "player_name": f"p{p}",
        "season": s,
        "league": lg,
        "games": g,
        "minutes": 30.0 * g,
        "rate": rate,
    }


def _test_rows(names, src=8.0):
    return pd.DataFrame(
        {
            "player_name": names,
            "league_src": ["spain-acb"] * len(names),
            "league_dest": ["euroleague"] * len(names),
            "pir_per36_src": [src] * len(names),
            "games_src": [15] * len(names),
        }
    )


def test_components_are_recovered_from_random_walk_data():
    """sigma^2 from shared-season stints, q from consecutive seasons, (mu, tau^2)
    from first seasons, beta from pairs -- all within tolerance of the truth.

    Mutation: drop the ``- noise`` term in ``q_from_consecutive_seasons`` -- q
    absorbs the sampling noise and comes out ~3x too large.
    """
    obs, pairs = _simulate(0)
    fit = vtd.fit_dynamic(obs, pairs, 2021)
    c = fit["components_used"]
    assert abs(c["sigma2_per_game"] - SIGMA2) < 3.0
    assert abs(fit["q"] - Q) < 0.35  # the q moment estimator is noisy at this n
    assert abs(c["tau2"] - TAU2) < 0.6
    assert abs(c["mu"] - MU) < 0.15
    for lg, b in BETA.items():
        assert abs(fit["beta"][lg] - b) < 0.15, (lg, fit["beta"][lg])
    assert not fit["q_info"]["q_floored"]
    assert not fit["sigma2_info"]["sigma2_floored"]


def test_sigma2_pairs_stints_of_the_same_player_season_only():
    """The two stints differenced are the two largest of ONE (player, season).

    Mutation: pair by original row order instead of by keys -- rows of
    different players get differenced and sigma^2 explodes (the bug the first
    smoke run had: 140 for a truth of 40).
    """
    stints = pd.DataFrame(
        {
            "player_name": ["a", "b", "a", "b", "c"],
            "season": [2018, 2018, 2018, 2018, 2018],
            "w": [10.0, 10.0, 10.0, 10.0, 10.0],
            # a's two stints agree; b's two stints agree; c has one stint
            "r": [5.0, 50.0, 5.0, 50.0, 100.0],
        }
    )
    out = vtd.sigma2_from_shared_seasons(stints)
    assert out["n_shared_season_pairs"] == 2
    assert out["sigma2_floored"]  # zero within-season difference -> floors, flagged


def test_q_scales_with_the_season_gap():
    """A two-season gap carries twice the innovation: E[d^2] = q * gap + noise.

    Mutation: drop ``gap`` from the denominator (sum of ones instead) -- q
    doubles on gapped data.
    """
    rng = np.random.default_rng(3)
    rows = []
    for p in range(4000):
        a = 0.0
        for s in (2016, 2018):  # every player skips 2017
            if s == 2018:
                a += rng.normal(0, np.sqrt(2 * Q))
            rows.append({"player_name": f"p{p}", "season": s, "rbar": a, "W": 1e9})
    means = pd.DataFrame(rows)
    out = vtd.q_from_consecutive_seasons(means, sigma2=1.0)
    assert abs(out["q"] - Q) < 0.1, out["q"]
    assert out["mean_gap"] == 2.0


def test_kalman_forecast_equals_the_scalar_recursion_and_grows_by_q():
    """Vectorised over players, the filter equals the textbook recursion on one
    player; the forecast variance grows by q per season since the last stint.

    Mutation: forget ``P += q * gap`` between observations -- the posterior
    over-trusts old seasons and m differs at the 4th decimal.
    """
    means = pd.DataFrame(
        {
            "player_name": ["a", "a", "a", "b"],
            "season": [2016, 2017, 2019, 2018],
            "rbar": [12.0, 9.0, 11.0, 7.0],
            "W": [20.0, 10.0, 30.0, 15.0],
        }
    )
    mu, tau2, s2, q = 10.0, 4.0, 40.0, 1.0
    out = vtd.kalman_forecast(means, 2021, mu=mu, tau2=tau2, sigma2=s2, q=q)
    out = out.set_index("player_name")
    m, P, prev = mu, tau2, None
    for s_, r, W in [(2016, 12.0, 20.0), (2017, 9.0, 10.0), (2019, 11.0, 30.0)]:
        if prev is not None:
            P += q * (s_ - prev)
        K = P / (P + s2 / W)
        m += K * (r - m)
        P = (1 - K) * P
        prev = s_
    P += q * (2021 - prev)
    assert np.isclose(out.loc["a", "m"], m) and np.isclose(out.loc["a", "P"], P)
    # b: one observation in 2018, forecast to 2021 -> P_post + 3q
    K_b = tau2 / (tau2 + s2 / 15.0)
    assert np.isclose(out.loc["b", "P"], (1 - K_b) * tau2 + 3 * q)
    assert out.loc["b", "n_seasons"] == 1


def test_q_zero_with_the_static_components_is_the_static_posterior():
    """T1: a Kalman filter with q = 0 and the static arm's (mu, tau^2, sigma^2)
    reduces to the precision-weighted shrinkage the static arm computes.

    Mutation: use ``P + R`` in place of ``P`` in the numerator of K -- the
    identity breaks at every row.
    """
    obs, pairs = _simulate(1, n_players=800)
    static = vth.fit_hierarchical(obs, pairs, 2021, scale="additive")
    exact = vtd.fit_dynamic(obs, pairs, 2021, q_zero=True, components=static["vc"])
    rows = _test_rows([f"p{i}" for i in range(50)])
    pe, _ = vtd.predict(exact, rows)
    ps = vth.predict(static, rows)
    assert np.max(np.abs(pe - ps)) < 1e-8


def test_nothing_from_the_scored_season_enters_its_own_fit():
    """Walk-forward discipline. Mutation: ``obs.season < season`` -> ``<=``."""
    obs, pairs = _simulate(2, n_players=600)
    rows = _test_rows(["p0"])
    base, _ = vtd.predict(vtd.fit_dynamic(obs, pairs, 2021), rows)
    planted = pd.concat(
        [obs, pd.DataFrame([_stint(0, 2021, "euroleague", 30, 60.0)])],
        ignore_index=True,
    )
    again, _ = vtd.predict(vtd.fit_dynamic(planted, pairs, 2021), rows)
    assert np.isclose(base[0], again[0])


def test_debutant_falls_back_to_the_shrunken_source_stint_and_is_flagged():
    """A player with no stint before S: mu + kappa (r_src - mu) + beta_D, flagged.

    Mutation: return the raw source rate for the fallback -- the flag stays but
    the value no longer shrinks toward mu.
    """
    fit = {
        "scale": "additive",
        "beta": {"euroleague": 0.0, "spain-acb": -1.5},
        "components_used": {"mu": 10.0, "tau2": 4.0, "sigma2_per_game": 40.0},
        "_forecast": pd.DataFrame(
            {"m": [11.0]}, index=pd.Index(["seen"], name="player_name")
        ),
    }
    rows = _test_rows(["seen", "nobody"], src=8.0)
    pred, fb = vtd.predict(fit, rows)
    assert fb.tolist() == [False, True]
    assert np.isclose(pred[0], 11.0)
    kappa = 4.0 / (4.0 + 40.0 / 15.0)
    assert np.isclose(pred[1], 10.0 + kappa * ((8.0 + 1.5) - 10.0))


def test_additive_prediction_is_not_clipped_at_zero():
    """Pre-registered: negative predictions are scored as they are and counted.

    Mutation: ``np.maximum(lin, 0)`` on the additive branch -- the value clips.
    """
    fit = {
        "scale": "additive",
        "beta": {"euroleague": 0.0, "spain-acb": -1.5},
        "components_used": {"mu": 10.0, "tau2": 4.0, "sigma2_per_game": 40.0},
        "_forecast": pd.DataFrame(
            {"m": [-3.0]}, index=pd.Index(["weak"], name="player_name")
        ),
    }
    pred, _ = vtd.predict(fit, _test_rows(["weak"]))
    assert pred[0] == -3.0


def test_verdict_rule_matches_the_preregistration():
    """PASS: dyn ahead, CI > 0. PARTIAL: CI spans zero. FAIL: combined ahead, CI < 0."""

    def sel(delta, lo, hi):
        return {
            "contrasts": {
                "dyn_vs_combined": {"delta_mae_b_minus_a": delta, "ci95": [lo, hi]}
            }
        }

    assert vtd.verdict(sel(0.1, 0.02, 0.18))["verdict"] == "PASS"
    assert vtd.verdict(sel(0.05, -0.02, 0.12))["verdict"] == "PARTIAL"
    assert vtd.verdict(sel(-0.03, -0.1, 0.04))["verdict"] == "PARTIAL"
    assert vtd.verdict(sel(-0.15, -0.25, -0.05))["verdict"] == "FAIL"
    assert vtd.PRIMARY == "dyn" and vtd.SELECTION_FOLDS == (
        2020,
        2021,
        2022,
        2023,
        2024,
    )


# ------------------------------------------------- Amendment 10: predict mode
def _primary(names, season=2021, status="draft"):
    return {
        "season": season,
        "status": status,
        "built_at": "2026-09-05",
        "source_collection": "synthetic.json",
        "basis": {"continental_source": "api"},
        "predictions": [
            {
                "person_code": f"c{i}",
                "name": n,
                "competition": "euroleague",
                "destination": "euroleague",
                "origin_league": "spain-acb",
                "pir_per36_src": 9.0 + i,
            }
            for i, n in enumerate(names)
        ],
    }


def test_predict_mode_emits_exactly_the_primary_population_and_flags_debutants():
    """One row per primary prediction, keyed by person_code + pairing_key; a name
    with no corpus history falls back and is flagged; the header carries the
    fitted components and the primary's status.

    Mutation: drop the last primary row from `out` before the assert -- the
    population-drift assert fires.
    """
    obs, pairs = _simulate(4, n_players=600)
    # the corpus loader keys every stint by pairing_key ("P0"); mirror that here
    # and give the primary the roster spellings the key must reconcile
    from src.data.corpus.euroleague_api import pairing_key

    obs = obs.assign(player_name=obs.player_name.map(pairing_key))
    pairs = pairs.assign(player_name=pairs.player_name.map(pairing_key))
    primary = _primary(["p0", "P1", "nobody here"])
    rows, header = vtd.predict_population(obs, pairs, primary, season=2021)
    assert [r["person_code"] for r in rows] == ["c0", "c1", "c2"]
    assert rows[0]["pairing_key"] == "P0" and rows[1]["pairing_key"] == "P1"
    assert [r["fallback"] for r in rows] == [False, False, True]
    assert rows[2]["n_seasons_used"] == 0 and rows[2]["last_season"] is None
    assert header["status"] == "draft" and header["n_predicted"] == 3
    assert header["fallback_share"] == pytest.approx(1 / 3)
    fresh = vtd.fit_dynamic(obs, pairs, 2021)
    assert header["components"]["q"] == pytest.approx(fresh["q"])
    assert header["components"]["tau2"] == pytest.approx(
        fresh["components_used"]["tau2"]
    )
    assert "interval_low" not in rows[0] and "interval" not in header


def test_predict_mode_refuses_a_population_that_drifts_from_the_primary(monkeypatch):
    """The write-time assert is the amendment's population clause made executable."""
    obs, pairs = _simulate(4, n_players=300)
    primary = _primary(["p0", "p1"])
    real_predict = vtd.predict

    def drop_one(fit, rows):
        pred, fb = real_predict(fit, rows)
        return pred[:-1], fb[:-1]  # one prediction short: must not pass silently

    monkeypatch.setattr(vtd, "predict", drop_one)
    with pytest.raises((AssertionError, IndexError)):
        vtd.predict_population(obs, pairs, primary, season=2021)
