"""Tests for ``scripts/validate_translation_hierarchical.py`` on synthetic data.

The script fits Proposition 4's model as one random-intercept model and scores
it walk-forward. None of these tests touch the corpus: each checks a property
the estimator must have on ANY data generated by the model it claims to fit --
the variance components are recovered, the shrinkage does what regression to
the mean does at both extremes, league effects come out with player ability
cancelled, and nothing from the scored season leaks into its own fit.

Each test names the mutation that breaks it; every mutation was applied to the
script, confirmed to fail, and reverted.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

import scripts.validate_translation_hierarchical as vth

pytestmark = pytest.mark.guard

LEAGUES = ("euroleague", "eurocup", "spain-acb", "italy-lba")
BETA = {"euroleague": 0.0, "eurocup": 0.10, "spain-acb": 0.12, "italy-lba": 0.20}
TAU2, SIGMA2, MU = 0.09, 0.36, 2.3


def _simulate(seed: int, n_players: int = 2500, seasons=(2016, 2017, 2018, 2019, 2020)):
    """Stints and same-season pairs from log rate = alpha_p + beta_L + noise."""
    rng = np.random.default_rng(seed)
    alpha = rng.normal(MU, np.sqrt(TAU2), n_players)
    stints, pairs = [], []
    for p in range(n_players):
        for s in seasons:
            lg = rng.choice(LEAGUES)
            g = int(rng.integers(8, 30))
            rate = np.exp(alpha[p] + BETA[lg] + rng.normal(0, np.sqrt(SIGMA2 / g)))
            stints.append(
                {
                    "player_name": f"p{p}",
                    "season": s,
                    "league": lg,
                    "games": g,
                    "minutes": 30.0 * g,
                    "rate": rate,
                }
            )
        if rng.random() < 0.4:
            s = int(rng.choice(seasons))
            src = rng.choice(["spain-acb", "italy-lba"])
            dst = rng.choice(["euroleague", "eurocup"])
            r1 = np.exp(alpha[p] + BETA[src] + rng.normal(0, np.sqrt(SIGMA2 / 15)))
            r2 = np.exp(alpha[p] + BETA[dst] + rng.normal(0, np.sqrt(SIGMA2 / 15)))
            pairs.append(
                {
                    "player_name": f"p{p}",
                    "season": s,
                    "league_src": src,
                    "league_dest": dst,
                    "pir_per36_src": r1,
                    "pir_per36_dest": r2,
                    "minutes_src": 450.0,
                    "minutes_dest": 450.0,
                }
            )
    return pd.DataFrame(stints), pd.DataFrame(pairs), alpha


def test_variance_components_recover_tau2_and_sigma2():
    """Method of moments under Var(eps_i) = sigma^2 / w_i recovers both components.

    Mutation: divide the within-player spread by ``n`` instead of ``n - 1`` --
    sigma^2 comes out ~20% low and tau^2 absorbs the difference.
    """
    obs, pairs, _ = _simulate(0)
    fit = vth.fit_hierarchical(obs, pairs, 2021)
    vc = fit["vc"]
    assert abs(vc["sigma2_per_game"] - SIGMA2) < 0.03
    assert abs(vc["tau2"] - TAU2) < 0.015
    assert abs(vc["mu"] - MU) < 0.03


def test_tau2_survives_players_with_near_zero_total_weight_and_flags_a_collapse():
    """DerSimonian-Laird tau^2 is not dragged to the floor by a few players whose
    weights sum to almost nothing (the recency-weight failure of the first run);
    and a population with NO between-player variance floors and says so.

    Mutation: restore the naive ``Var_p(rbar) - mean_p(sigma^2 / W_p)`` -- the
    tiny-W players push the mean term past the variance and tau^2 floors.
    """
    rng = np.random.default_rng(5)
    n_players, sigma2, tau2 = 3000, 0.36, 0.09
    alpha = rng.normal(0.0, np.sqrt(tau2), n_players)
    resid, w, players = [], [], []
    for p in range(n_players):
        weights = rng.integers(8, 30, size=4).astype(float)
        if p % 10 == 0:  # one in ten carries almost no weight
            weights = weights * 1e-3
        for wt in weights:
            resid.append(alpha[p] + rng.normal(0, np.sqrt(sigma2 / wt)))
            w.append(wt)
            players.append(f"p{p}")
    vc = vth.variance_components(np.array(resid), np.array(w), np.array(players))
    assert not vc["tau2_floored"]
    assert abs(vc["tau2"] - tau2) < 0.02, vc["tau2"]
    assert abs(vc["sigma2_per_game"] - sigma2) < 0.03
    flat = vth.variance_components(
        rng.normal(0, np.sqrt(sigma2 / 20), 4000),
        np.full(4000, 20.0),
        np.repeat([f"p{i}" for i in range(1000)], 4),
    )
    assert flat["tau2_floored"]
    assert flat["tau2"] == vth.TAU2_FLOOR


def test_league_effects_from_pairs_cancel_player_ability():
    """P4(i) inside the estimator: beta from same-season pairs is unaffected by
    alpha_p even when only strong players reach the continental side.

    Mutation: use ``pir_per36_dest - pir_per36_src`` (additive) on the log
    arm -- beta then scales with the rate level and misses by > 0.05.
    """
    obs, pairs, alpha = _simulate(1)
    strong = pd.Series(alpha, index=[f"p{i}" for i in range(len(alpha))])
    pairs = pairs[pairs.player_name.map(strong) > MU]  # selection through alpha
    beta = vth.league_effects_from_pairs(pairs, "euroleague")
    for lg, b in BETA.items():
        assert abs(beta[lg] - b) < 0.03, (lg, beta[lg], b)


def test_joint_league_effects_agree_with_pairs_route():
    """Within-player demeaned WLS on every stint recovers the same beta.

    Mutation: skip the demeaning (regress on raw X) -- alpha_p is no longer
    removed and beta shifts by the selection into leagues.
    """
    obs, pairs, _ = _simulate(2)
    value = np.log(obs.rate.clip(lower=vth.RATE_FLOOR)).to_numpy()
    beta = vth.league_effects_joint(obs, value, "euroleague")
    for lg, b in BETA.items():
        assert abs(beta[lg] - b) < 0.03, (lg, beta[lg], b)


def test_shrinkage_is_regression_to_the_mean_at_both_extremes():
    """kappa -> 1 when the player is far better measured than the population
    varies (own mean wins); kappa -> 0 when tau^2 -> 0 (grand mean wins).

    Mutation: swap tau^2 and sigma^2/W in kappa -- the limits invert.
    """
    rbar = pd.Series({"a": 3.0, "b": 1.0})
    W = pd.Series({"a": 1e6, "b": 1e6})
    vc = {"mu": 2.0, "tau2": 1.0, "sigma2_per_game": 1.0, "_rbar": rbar, "_W": W}
    own = vth.posterior_alpha(vc, pd.Series(["a", "b"]))
    assert np.allclose(own, [3.0, 1.0], atol=1e-4)
    vc_flat = dict(vc, tau2=1e-9)
    grand = vth.posterior_alpha(vc_flat, pd.Series(["a", "b"]))
    assert np.allclose(grand, [2.0, 2.0], atol=1e-3)


def test_prediction_is_posterior_alpha_plus_destination_effect():
    """yhat = exp(E[alpha_p | history] + beta_D); a player with no history falls
    back to a shrunken source stint.

    Mutation: add ``sigma^2/2`` to the exponent (lognormal mean) -- the
    MAE-optimal median is what the script promises, and this test moves.
    """
    fit = {
        "beta": {"euroleague": 0.0, "spain-acb": 0.2},
        "vc": {
            "mu": 2.0,
            "tau2": 0.1,
            "sigma2_per_game": 0.4,
            "_rbar": pd.Series({"seen": 2.5}),
            "_W": pd.Series({"seen": 40.0}),
        },
        "scale": "log",
    }
    rows = pd.DataFrame(
        {
            "player_name": ["seen", "unseen"],
            "league_src": ["spain-acb", "spain-acb"],
            "league_dest": ["euroleague", "euroleague"],
            "pir_per36_src": [12.0, 12.0],
            "games_src": [20, 20],
        }
    )
    pred = vth.predict(fit, rows)
    kappa = 0.1 / (0.1 + 0.4 / 40.0)
    assert np.isclose(pred[0], np.exp(2.0 + kappa * 0.5))
    k2 = 0.1 / (0.1 + 0.4 / 20.0)
    src_val = np.log(12.0) - 0.2
    assert np.isclose(pred[1], np.exp(2.0 + k2 * (src_val - 2.0)))


def test_nothing_from_the_scored_season_enters_its_own_fit():
    """Walk-forward discipline: a stint in season S must not move the fit for S.

    Mutation: change ``obs.season < season`` to ``<=`` -- the planted season-S
    row shifts the player's posterior and the test fails.
    """
    obs, pairs, _ = _simulate(3)
    base = vth.predict(
        vth.fit_hierarchical(obs, pairs, 2021),
        pd.DataFrame(
            {
                "player_name": ["p0"],
                "league_src": ["spain-acb"],
                "league_dest": ["euroleague"],
                "pir_per36_src": [10.0],
                "games_src": [20],
            }
        ),
    )
    planted = pd.concat(
        [
            obs,
            pd.DataFrame(
                [
                    {
                        "player_name": "p0",
                        "season": 2021,
                        "league": "euroleague",
                        "games": 30,
                        "minutes": 900.0,
                        "rate": 60.0,
                    }
                ]
            ),
        ],
        ignore_index=True,
    )
    again = vth.predict(
        vth.fit_hierarchical(planted, pairs, 2021),
        pd.DataFrame(
            {
                "player_name": ["p0"],
                "league_src": ["spain-acb"],
                "league_dest": ["euroleague"],
                "pir_per36_src": [10.0],
                "games_src": [20],
            }
        ),
    )
    assert np.isclose(base[0], again[0])


def test_no_league_arm_has_zero_league_effects_and_short_stints_are_dropped():
    """The decomposition arm removes beta entirely; the stint floor is applied.

    Mutation: drop the ``minutes >= MIN_STINT_MINUTES`` filter -- the
    one-minute stint survives and its per-36 rate (2160) enters the fit.
    """
    obs, pairs, _ = _simulate(4, n_players=300)
    fit = vth.fit_hierarchical(obs, pairs, 2021, no_league=True)
    assert set(fit["beta"].values()) == {0.0}
    games = pd.DataFrame(
        {
            "player_name": ["x", "x", "y"],
            "season": [2018, 2018, 2018],
            "league": ["euroleague", "euroleague", "eurocup"],
            "game_id": [1, 2, 3],
            "minutes": [1.0, 0.5, 40.0],
            "pir": [60.0, 0.0, 10.0],
        }
    )
    rows = vth.player_season_league_rows(games)
    assert rows.player_name.tolist() == ["y"]
    assert np.isclose(rows.rate.iloc[0], 9.0)


def test_primary_arm_is_declared_and_disjoint_from_the_alternatives():
    """The claim is the declared primary; alternatives and decomposition are
    printed beside it, never in its place."""
    assert vth.PRIMARY == "hier"
    assert vth.PRIMARY not in vth.ALTERNATIVES
    assert vth.PRIMARY not in vth.DECOMPOSITION
    assert not set(vth.ALTERNATIVES) & set(vth.DECOMPOSITION)


def test_tier_beta_keeps_the_level_and_removes_the_mapping():
    """Domestic effects collapse to one pair-weighted mean; continental ones and
    leagues without pairs are untouched. Mutation: weight by 1 instead of the
    pair count -- the mean moves off 0.15 toward 0.10."""
    beta = {
        "euroleague": 0.0,
        "eurocup": 0.1,
        "spain-acb": 0.2,
        "italy-lba": 0.0,
        "x": 0.9,
    }
    pairs = pd.DataFrame({"league_src": ["spain-acb"] * 3 + ["italy-lba"]})
    out = vth.collapse_domestic_to_tier(beta, pairs)
    assert out["euroleague"] == 0.0 and out["eurocup"] == 0.1 and out["x"] == 0.9
    assert np.isclose(out["spain-acb"], 0.15) and np.isclose(out["italy-lba"], 0.15)


def test_naive_tau2_estimator_is_still_runnable_for_the_run2_record(monkeypatch):
    """``--tau2-estimator naive`` must reproduce the first two runs' form."""
    rng = np.random.default_rng(9)
    resid = rng.normal(0, 0.5, 400)
    w = np.full(400, 10.0)
    players = np.repeat([f"p{i}" for i in range(100)], 4)
    monkeypatch.setattr(vth, "TAU2_ESTIMATOR", "naive")
    naive = vth.variance_components(resid, w, players)
    monkeypatch.setattr(vth, "TAU2_ESTIMATOR", "dl")
    dl = vth.variance_components(resid, w, players)
    # equal weights: DL and the naive form agree to sampling arithmetic
    assert abs(naive["tau2_raw"] - dl["tau2_raw"]) < 0.02
